invitingly/calendarMonths/urls.py
from django.urls import path

from . import views

app_name = "cale"

# Create your urls here.
urlpatterns = [
    path('calendar/', views.calendar_view, name='calendar'),
]

invitingly/invite/urls.py
from django.urls import path

from . import views

app_name = "invite"

# Create your urls here.
urlpatterns = [
    # path('', views._view, name=''),
    path('questionclick', views.questionclick_view, name="questionclick_view"),
    path('givemoneyclick', views.givemoney_view, name="givemoney_view"),
    path('notattendclick', views.notattend_view, name="notattend_view"),
]

invitingly/invitingly/urls.py
from django.contrib import admin
# from invitingly import *
from django.contrib.auth import views
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from information.forms import UserLoginForm, ResetPasswordForm, NewPasswordForm
from information.views import home_view, aboutus_view, contactus_view, afterlogin_view, adminclick_view, \
    admin_signup_view, admin_dashboard_view

urlpatterns = [
    # add a app
    path('', include('information.urls')),
    # path('student/', include('student.urls')),
    path('calendarMonths/', include('calendarMonths.urls')),
    path('invite/', include('invite.urls')),

    path('admin/', admin.site.urls),


    # 未加入會員的 navbars 可供新客戶觀看
    path('', home_view, name='home'),
    path('logout', LogoutView.as_view(template_name='info/logout.html'), name='logout'),
    # path('logout/', views.LogoutView.as_view(), name="logout"),

    path('aboutus', aboutus_view, name='aboutus'),
    path('contactus', contactus_view, name='contactus'),
    path('afterlogin', afterlogin_view, name='afterlogin'),

    path('adminclick', adminclick_view, name='adminclick'),
    path('adminlogin', LoginView.as_view(template_name='info/adminlogin.html', authentication_form=UserLoginForm), name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=UserLoginForm),name="login"),

    path('adminsignup', admin_signup_view, name='adminsignup'),
    # path('signup/', signup, name="signup"),

    path('admin-dashboard', admin_dashboard_view, name='admin-dashboard'),
    # path('adminlogin', LoginView.as_view(template_name='info/login.html'), authentication_form=AdminUserLoginForm, name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=AdminUserLoginForm),name="login"),


    # 對於忘記密碼 可以有另一個分支
    path('password-reset/',
         views.PasswordResetView.as_view(template_name="info/reset_password.html", form_class=ResetPasswordForm),
         name="password_reset"),

    path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name="info/reset_password_done.html"),
         name="password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name="info/reset_password_confirm.html",
                                                form_class=NewPasswordForm), name="password_reset_confirm"),

    path('password-reset-complete/',
         views.PasswordResetCompleteView.as_view(template_name="info/reset_password_complete.html"),
         name="password_reset_complete"),

]

invitingly/templates/_includes/content.html
{% load static %}

<div class="overview-boxes">
    <div class="box">
        <div class="right-side">
            <div class="box-topic">Total Order</div>
            <div class="number">40,876</div>
            <div class="indicator">
                <i class='bx bx-up-arrow-alt'></i>
                <span class="text">Up from yesterday</span>
            </div>
        </div>
        <i class='bx bx-cart-alt cart'></i>
    </div>
    <div class="box">
        <div class="right-side">
            <div class="box-topic">Total Sales</div>
            <div class="number">38,876</div>
            <div class="indicator">
                <i class='bx bx-up-arrow-alt'></i>
                <span class="text">Up from yesterday</span>
            </div>
        </div>
        <i class='bx bxs-cart-add cart two'></i>
    </div>
    <div class="box">
        <div class="right-side">
            <div class="box-topic">Total Profit</div>
            <div class="number">$12,876</div>
            <div class="indicator">
                <i class='bx bx-up-arrow-alt'></i>
                <span class="text">Up from yesterday</span>
            </div>
        </div>
        <i class='bx bx-cart cart three'></i>
    </div>
    <div class="box">
        <div class="right-side">
            <div class="box-topic">Total Return</div>
            <div class="number">11,086</div>
            <div class="indicator">
                <i class='bx bx-down-arrow-alt down'></i>
                <span class="text">Down From Today</span>
            </div>
        </div>
        <i class='bx bxs-cart-download cart four'></i>
    </div>
</div>
<div class="sales-boxes">
    <div class="recent-sales box">
        <div class="title">Recent Sales</div>
        <div class="sales-details">
            <ul class="details">
                <li class="topic">Date</li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
                <li><a href="#">02 Jan 2021</a></li>
            </ul>
            <ul class="details">
                <li class="topic">Customer</li>
                <li><a href="#">Alex Doe</a></li>
                <li><a href="#">David Mart</a></li>
                <li><a href="#">Roe Parter</a></li>
                <li><a href="#">Diana Penty</a></li>
                <li><a href="#">Martin Paw</a></li>
                <li><a href="#">Doe Alex</a></li>
                <li><a href="#">Aiana Lexa</a></li>
                <li><a href="#">Rexel Mags</a></li>
                <li><a href="#">Tiana Loths</a></li>
            </ul>
            <ul class="details">
                <li class="topic">Sales</li>
                <li><a href="#">Delivered</a></li>
                <li><a href="#">Pending</a></li>
                <li><a href="#">Returned</a></li>
                <li><a href="#">Delivered</a></li>
                <li><a href="#">Pending</a></li>
                <li><a href="#">Returned</a></li>
                <li><a href="#">Delivered</a></li>
                <li><a href="#">Pending</a></li>
                <li><a href="#">Delivered</a></li>
            </ul>
            <ul class="details">
                <li class="topic">Total</li>
                <li><a href="#">$204.98</a></li>
                <li><a href="#">$24.55</a></li>
                <li><a href="#">$25.88</a></li>
                <li><a href="#">$170.66</a></li>
                <li><a href="#">$56.56</a></li>
                <li><a href="#">$44.95</a></li>
                <li><a href="#">$67.33</a></li>
                <li><a href="#">$23.53</a></li>
                <li><a href="#">$46.52</a></li>
            </ul>
        </div>
        <div class="button">
            <a href="#">See All</a>
        </div>
    </div>
    <div class="top-sales box">
        <div class="title">Top Seling Product</div>
        <ul class="top-sales-details">
            <li>
                <a href="#">
                    <img src="{% static 'images/sunglasses.jpg' %}" alt="">
                    <span class="product">Vuitton Sunglasses</span>
                </a>
                <span class="price">$1107</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/jeans.jpg' %}" alt="">
                    <span class="product">Hourglass Jeans </span>
                </a>
                <span class="price">$1567</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/nike.jpg' %}" alt="">
                    <span class="product">Nike Sport Shoe</span>
                </a>
                <span class="price">$1234</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/scarves.jpg' %}" alt="">
                    <span class="product">Hermes Silk Scarves.</span>
                </a>
                <span class="price">$2312</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/blueBag.jpg' %}" alt="">
                    <span class="product">Succi Ladies Bag</span>
                </a>
                <span class="price">$1456</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/bag.jpg' %}" alt="">
                    <span class="product">Gucci Womens's Bags</span>
                </a>
                <span class="price">$2345</span>
            <li>
                <a href="#">
                    <img src="{% static 'images/addidas.jpg' %}" alt="">
                    <span class="product">Addidas Running Shoe</span>
                </a>
                <span class="price">$2345</span>
            </li>
            <li>
                <a href="#">
                    <img src="{% static 'images/shirt.jpg' %}" alt="">
                    <span class="product">Bilack Wear's Shirt</span>
                </a>
                <span class="price">$1245</span>
            </li>
        </ul>
    </div>
</div>

invitingly/templates/_includes/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
        padding: 0!important;
	}

</style>
<!-- Footer -->
<br>
<div class="d-flex flex-row align-items-center footer  bg-white border-top shadow-lg">
    <!--	<p class="m-auto">CodingWithMitch Blog Course | 2019</p>-->
<!--    <p class="m-auto"> 婚禮小幫手 ERP | 2023</p>-->
        <p class="m-auto">
			<font style="vertical-align: inherit;"><font style="vertical-align: inherit;">婚禮小幫手 ERP&nbsp;&nbsp;|&nbsp;&nbsp; ®MIT </font></font><br>
			<font style="vertical-align: inherit;"><font style="vertical-align: inherit;">魚子匠版權所有 © Online Wedding 2024</font></font></p>
</div>
<!-- End Footer -->

invitingly/templates/_includes/header.html
{% load static %}

<div class="bs-example">
    <nav class="navbar navbar-expand-md  navbar-dark bg-secondary fixed-top p-2 px-md-4 mb-3"
         style="background-color: #000000;">
        <!--{#        <a style="color: #ffffff;text-decoration: none; " href="/"><font face="Comic sans MS" size="5">婚宴#}-->
        <!--{#            小助手</font><br/></a>#}-->
        <a class="navbar-item" href="/">
            <img src="{% static 'img/django_logo.png' %}"
                 width="100px" height="40px">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav">
                <a style="padding-left: 30px;" href="/" class="nav-item nav-link active">首頁</a>
                <a href="{% url 'invite:questionclick_view' %}" class="nav-item nav-link">邀請函-貴賓</a>
                <a href="{% url 'cale:calendar' %}" class="nav-item nav-link">日曆</a>
                <a href="{% url 'aboutus' %}" class="nav-item nav-link">關於我</a>
                <a href="{% url 'contactus' %}" class="nav-item nav-link">聯繫我</a>
            </div>
            <div class="navbar-nav">
<!--                <a href="/adminsignup" class="nav-item nav-link btn btn-outline-primary">管理員-註冊</a>-->
                <a href="{% url 'adminsignup' %}" class="nav-item nav-link btn btn-outline-primary">管理員-註冊</a>
<!--                <a href="/adminclick" class="nav-item nav-link">管理員-登入</a>-->
                <a href="{% url 'adminclick' %}" class="nav-item nav-link">管理員-登入</a>
            </div>
        </div>
    </nav>
</div>
<!-- End Header -->

invitingly/templates/_includes/header2.html
{% load static %}

<style type="text/css">
    @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
    }

    .search-bar {
        max-width: 500px;
        width: 100%;
    }

    form {
        width: 100%;
    }

</style>

<!-- Header -->
<div class="bs-example">
    <nav class="navbar navbar-expand-md  navbar-dark fixed-top" style="background-color: #000000;">
        <a style="color: #ffffff;text-decoration: none; " href="/"><font face="Comic sans MS" size=" 5">Online
            Quiz</font><br/></a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav">
                <a style="
          padding-left: 30px;
      " href="/" class="nav-item nav-link active">Home</a>

                <a href="/teacher/teacherclick" class="nav-item nav-link">Teacher</a>
                <a href="/student/studentclick" class="nav-item nav-link">Student</a>
                <a href="/adminclick" class="nav-item nav-link">Admin</a>
                <a href="/adminsignup" class="nav-item nav-link">Signup</a>


            </div>

            <div class="navbar-nav">
                <a href="/aboutus" class="nav-item nav-link">About Us</a>
                <a href="/contactus" class="nav-item nav-link">Contact Us</a>

            </div>


        </div>
    </nav>
</div>

invitingly/templates/_includes/link.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description"
      content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">

<!-- fontawesome CSS -->
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!-- datatables.net CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

<!-- 本地端 Local CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

invitingly/templates/_includes/links.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!--{#針對html class的hero is-fullheight 設計#}-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">

<!--{# 本地端畫面修改css #}-->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

invitingly/templates/_includes/nav.html
{% load static %}
<nav>
    <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">Dashboard</span>
    </div>
    <div class="search-box">
        <input type="text" placeholder="Search...">
        <i class='bx bx-search'></i>
    </div>
    <div class="profile-details">
        <img src="images/profile.jpg" alt="">
        <span class="admin_name">Prem Shahi</span>
        <i class='bx bx-chevron-down'></i>
    </div>
</nav>

invitingly/templates/_includes/script.html
{% load static %}
<!-- jquery -->
<script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
        crossorigin="anonymous"></script>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
<!-- Font Awesome CDN embed code! -->
<script src="https://use.fontawesome.com/abbbfbddac.js"></script>

<!-- 本地端 Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

invitingly/templates/_includes/sidebar.html
{% load static %}

<div class="logo-details">
    <i class='bx bxl-c-plus-plus'></i>
    <span class="logo_name">CodingLab</span>
</div>
<ul class="nav-links">
    <li>
        <a href="{% url 'marryApp:index' %}">
            <i class='bx bx-coin-stack'></i>
            <span class="links_name">Dashboard INFO</span>
        </a>
    </li>
    <li>
        <a href="{% url 'marryApp:marry_add' %}" class="active">
            <i class='bx bx-grid-alt'></i>
            <span class="links_name">新增賓客(add)</span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class='bx bx-box'></i>
            <span class="links_name">賓客資訊(list search)</span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class='bx bx-list-ul'></i>
            <span class="links_name">賓客修改(del)</span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class='bx bx-pie-chart-alt-2'></i>
            <span class="links_name">Analytics</span>
        </a>
    </li>
<!--    /////-->
<!--    <li>-->
<!--        <a href="#">-->
<!--            <i class='bx bx-book-alt'></i>-->
<!--            <span class="links_name">Total order</span>-->
<!--        </a>-->
<!--    </li>-->
<!--    <li>-->
<!--        <a href="#">-->
<!--            <i class='bx bx-user'></i>-->
<!--            <span class="links_name">Team</span>-->
<!--        </a>-->
<!--    </li>-->
<!--    <li>-->
<!--        <a href="#">-->
<!--            <i class='bx bx-message'></i>-->
<!--            <span class="links_name">Messages</span>-->
<!--        </a>-->
<!--    </li>-->
<!--    ///////-->
    <li>
        <a href="#">
            <i class='bx bx-heart'></i>
            <span class="links_name">Favrorites</span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class='bx bx-cog'></i>
            <span class="links_name">Setting</span>
        </a>
    </li>
    <li class="log_out">
        <a href="#">
            <i class='bx bx-log-out'></i>
            <span class="links_name">Log out</span>
        </a>
    </li>
</ul>