invitingly/information/urls.py
from django.urls import path

from . import views

app_name = "info"

# Create your urls here.
urlpatterns = [
    # path('admin-student', views.admin_student_view, name='admin-student'),

]

invitingly/invite/urls.py
from django.urls import path

from . import views

app_name = "invite"

# Create your urls here.
urlpatterns = [
    # path('', views._view, name=''),
    path('questionclick', views.questionclick_view, name="questionclick_view"),
    path('givemoneyclick', views.givemoney_view, name="givemoney_view"),
    path('notattendclick', views.notattend_view, name="notattend_view"),
]

invitingly/invitingly/urls.py
from django.contrib import admin
# from invitingly import *
from django.contrib.auth import views
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from information.forms import UserLoginForm, ResetPasswordForm, NewPasswordForm
from information.views import home_view, aboutus_view, contactus_view, afterlogin_view, adminclick_view, \
    admin_signup_view, admin_dashboard_view

urlpatterns = [
    # add a app
    path('', include('information.urls')),
    # path('student/', include('student.urls')),
    path('calendarMonths/', include('calendarMonths.urls')),
    path('invite/', include('invite.urls')),

    path('admin/', admin.site.urls),


    # 未加入會員的 navbars 可供新客戶觀看
    path('', home_view, name='home'),
    path('logout', LogoutView.as_view(template_name='info/logout.html'), name='logout'),
    # path('logout/', views.LogoutView.as_view(), name="logout"),

    path('aboutus', aboutus_view, name='aboutus'),
    path('contactus', contactus_view, name='contactus'),
    path('afterlogin', afterlogin_view, name='afterlogin'),

    path('adminclick', adminclick_view, name='adminclick'),
    path('adminlogin', LoginView.as_view(template_name='info/adminlogin.html', authentication_form=UserLoginForm), name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=UserLoginForm),name="login"),

    path('adminsignup', admin_signup_view, name='adminsignup'),
    # path('signup/', signup, name="signup"),

    path('admin-dashboard', admin_dashboard_view, name='admin-dashboard'),
    # path('adminlogin', LoginView.as_view(template_name='info/login.html'), authentication_form=AdminUserLoginForm, name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=AdminUserLoginForm),name="login"),


    # 對於忘記密碼 可以有另一個分支
    path('password-reset/',
         views.PasswordResetView.as_view(template_name="info/reset_password.html", form_class=ResetPasswordForm),
         name="password_reset"),

    path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name="info/reset_password_done.html"),
         name="password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name="info/reset_password_confirm.html",
                                                form_class=NewPasswordForm), name="password_reset_confirm"),

    path('password-reset-complete/',
         views.PasswordResetCompleteView.as_view(template_name="info/reset_password_complete.html"),
         name="password_reset_complete"),

]

invitingly/templates/info/admin_dashboard.html
{% extends 'info/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}


<h2>公告大小事</h2>
<hr>
<div class="row">
    <div class="form-group col-md-12">
        <p>This is a responsive sidebar template with dropdown menu based on bootstrap 4 framework.</p>
        <p> You can find the complete code on <a href="https://github.com/azouaoui-med/pro-sidebar-template"
                                                 target="_blank">
            Github</a>, it contains more themes and background image option</p>
    </div>
    <div class="form-group col-md-12">
        <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=star&count=true&size=large"
                frameborder="0" scrolling="0" width="140px" height="30px"></iframe>
        <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=fork&count=true&size=large"
                frameborder="0" scrolling="0" width="140px" height="30px"></iframe>
    </div>
</div>
<h5>More templates</h5>
<hr>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/53659076-e2204680-3c5a-11e9-8c00-0c10bcd945e6.jpg"
                 class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
                <h6 class="card-title">Angular Pro Sidebar</h6>
                <a href="https://github.com/azouaoui-med/angular-pro-sidebar" target="_blank"
                   class="btn btn-primary btn-sm">Github</a>
                <a href="https://azouaoui-med.github.io/angular-pro-sidebar/demo/" target="_blank"
                   class="btn btn-success btn-sm">Preview</a>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/53659497-016ba380-3c5c-11e9-8dfd-4901ddaf090b.jpg"
                 class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
                <h6 class="card-title">Angular Dashboard</h6>
                <a href="https://github.com/azouaoui-med/lightning-admin-angular" target="_blank"
                   class="btn btn-primary btn-sm">Github</a>
                <a href="https://azouaoui-med.github.io/lightning-admin-angular/demo/" target="_blank"
                   class="btn btn-success btn-sm">Preview</a>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

invitingly/templates/info/admin_dashboard1.html
{% extends 'info/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}


    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <style type="text/css">
            a:link {
                text-decoration: none;
            }

            .order-card {
                color: rgb(255, 255, 255);
            }

            .bg-c-blue {
                background: #04868f;
            }

            .bg-c-green {
                background: #4C51BF;
            }

            .bg-c-yellow {
                background: #F56565;
            }

            .bg-c-pink {
                background: #663a30;
            }


            .card {

                -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
                box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
                border: 1px solid black;
                margin-bottom: 30px;
                -webkit-transition: all 0.3s ease-in-out;
                transition: all 0.3s ease-in-out;
            }

            .card .card-block {
                padding: 25px;
            }

            .order-card i {
                font-size: 26px;
            }

            .f-left {
                float: left;
            }

            .f-right {
                float: right;
            }

            header {
                left: 0px;
                right: 0px;
            }
        </style>
    </head>
    <br><br>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xl-3">
                <div class="card bg-c-blue order-card">
                    <div class="card-block">
                        <h6 class="m-b-20"><a href="admin-view-student" style="text-decoration: none;color:white;">Total
                            Students</a></h6>
                        <h2 class="text-right"><i
                                class="fas fa-user-graduate f-left"></i><span>{{ total_student }}</span></h2>

                    </div>
                </div>
            </div>

            <div class="col-md-4 col-xl-3">
                <div class="card bg-c-green order-card">
                    <div class="card-block">
                        <h6 class="m-b-20"><a href="admin-view-teacher" style="text-decoration: none;color:white;">Total
                            Teacher</a></h6>
                        <h2 class="text-right"><i
                                class="fas fa-chalkboard-teacher f-left"></i><span>{{ total_teacher }}</span></h2>

                    </div>
                </div>
            </div>

            <div class="col-md-4 col-xl-3">
                <div class="card bg-c-yellow order-card">
                    <div class="card-block">
                        <h6 class="m-b-20"><a href="admin-view-course" style="text-decoration: none;color:white;">Total
                            Courses</a></h6>
                        <h2 class="text-right"><i class="fas fa-book f-left"></i><span>{{ total_course }}</span></h2>

                    </div>
                </div>
            </div>

            <div class="col-md-4 col-xl-3">
                <div class="card bg-c-pink order-card">
                    <div class="card-block">
                        <h6 class="m-b-20"><a href="admin-view-question" style="text-decoration: none;color:white;">Total
                            Questions</a></h6>
                        <h2 class="text-right"><i
                                class="fas fa-question-circle f-left"></i><span>{{ total_question }}</span></h2>

                    </div>
                </div>
            </div>


        </div>
    </div>


    <br><br><br><br><br><br><br><br><br><br>

    <script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

invitingly/templates/info/admin_dashboard2.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <style media="screen">
        a:link {
            text-decoration: none;
        }

        body {
            margin: 0;
            padding: 0;
            font-family: "Gill Sans", sans-serif;;
        }

        header {
            position: fixed;
            background: #22242A;
            padding: 20px;
            width: 100%;
            z-index: 1;
        }

        .left_area h3 {
            color: #fff;
            margin: 0px;
            text-transform: uppercase;
            font-size: 22px;
            font-weight: 900;
        }

        .left_area span {
            color: #19B3D3;
        }

        .logout_btn {
            padding: 5px;
            background: #19B3D3;
            text-decoration: none;
            float: right;
            margin-top: -30px;
            margin-right: 40px;
            border-radius: 2px;
            font-size: 15px;
            font-weight: 600;
            color: #fff;
            transition: 0.5s;

        }

        .logout_btn:hover {
            background: #0B87A6;
        }

        .sidebar {
            background: #2f323a;
            margin-top: 70px;
            padding-top: 30px;
            position: fixed;
            left: 0;
            width: 250px;
            height: 100%;
            transition: 0.5s;
            transition-property: left;
        }

        .sidebar .profile_image {
            width: 100px;
            height: 100px;
            border-radius: 100px;
            margin-bottom: 10px;
        }

        .sidebar h4 {
            color: #ccc;
            margin-top: 0;
            margin-bottom: 20px;
        }

        .sidebar a {
            color: #fff;
            display: block;
            width: 100%;
            line-height: 60px;
            text-decoration: none;
            padding-left: 40px;
            box-sizing: border-box;
            transition: 0.5s;

        }

        .sidebar a:hover {
            background: #19B3D3;
        }

        .sidebar i {
            padding-right: 10px;
        }

        label #sidebar_btn {
            z-index: 1;
            color: #fff;
            position: fixed;
            cursor: pointer;
            left: 300px;
            font-size: 20px;
            margin: 5px 0;
            transition: 0.5s;
            transition-property: color;
        }

        label #sidebar_btn:hover {
            color: #19B3D3;
        }

        #check:checked ~ .sidebar {
            left: -190px;

        }

        #check:checked ~ .sidebar a span {
            display: none;
        }

        #check:checked ~ .sidebar a {
            font-size: 20px;
            margin-left: 170px;
            width: 80px;
        }

        .content {
            margin-left: 250px;
            background: url(background.png) no-repeat;
            background-position: center;
            background-size: cover;
            height: 100vh;
            transition: 0.5s;
        }

        #check:checked ~ .content {
            margin-left: 60px;
        }

        #check {
            display: none;
        }


    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
</head>
<style>
* {
<!--    outline:1px solid red;-->
}
.sidebar h6 {
    color: #ccc;
<!--    margin-top: 0;-->
    margin:0;
    margin-bottom: 20px;
}

.h6, h6 {
    font-size: 1.5rem;
    wid
}

img.img-responsive.img-rounded{
    
}

</style>
<body>

<input type="checkbox" id="check">
<!--header area start-->
<header>
    <label for="check">
        <i style="left: 200px;margin-top: 17px;" class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
        <h3>Online Quiz</h3>
    </div>
    <div class="right_area">
        <a href="{% url 'info:logout'%}" class="logout_btn">Logout</a>
    </div>
</header>
<!--header area end-->
<!--sidebar start-->
<div class="sidebar">
    <center>
        <img src="{% static 'image/admin.png' %}" class="profile_image" alt="">
        <h6>
            <!-- Admin -->
            {% if request.user.is_authenticated %}
            <a class="p-0">Welcome,{{ user.username }}</a>
<!--            has-text-light m0-->
            {% endif %}
        </h6>
    </center>

    <a href="/admin-dashboard"><i class="fas fa-tachometer-alt"></i><span>首頁</span></a>
    <a href="/admin-teacher"><i class="fas fa-chalkboard-teacher"></i><span>老師</span></a>
    <a href="/admin-student"><i class="fas fa-user-graduate"></i><span>學生</span></a>
    <a href="/admin-course"><i class="fas fa-book"></i><span>Courses課程</span></a>
    <a href="/admin-question"><i class="fas fa-question-circle"></i><span>Questions問題</span></a>


</div>
<!--sidebar end-->


<!--content start-->
<div class="content">
    <br><br><br><br><br>
    {% block content %}
    {% endblock content %}

    <br><br><br>
    {% include "_includes/footer.html" %}
</div>
<!--content end-->
</body>

</html>











{% load static %}

<style>
    .logout_btn }
        padding: 5px;
        background: #19B3D3;
        text-decoration: none;
        float: right;
        margin-top: -30px;
        margin-right: 40px;
        border-radius: 2px;
        font-size: 15px;
        font-weight: 600;
        color: #fff;
        transition: 0.5s;

     }

    .logout_btn:hover }
        background: #0B87A6;
     }
</style>
<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
        <div class="sidebar-brand">
            <a href="{% url 'info:home' %}">婚禮側邊欄位</a>
            <div id="close-sidebar">
                <i class="fas fa-times"></i>
            </div>
        </div>
        <div class="sidebar-header">
            <div class="user-pic">
                <img class="img-responsive img-rounded"
                     src="http://fakeimg.pl/200x200"
                     alt="User picture">
            </div>
            <div class="user-info">
          <span class="user-name">Jhon
            <strong>Smith</strong>
          </span>
                <span class="user-role">Administrator</span>
                <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
            </div>
        </div>
        <!-- sidebar-header  -->
        <div class="sidebar-search">
            <div>
                <div class="input-group">
                    <input type="text" class="form-control search-menu" placeholder="Search...">
                    <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
                    </div>
                </div>
            </div>
        </div>
        <!-- sidebar-search  -->
        <div class="sidebar-menu">
            <ul>
                <li class="header-menu">
                    <span>General</span>
                </li>
                <li>
                    <a href="{% url 'info:admin-dashboard' %}">
                        <i class="fa fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-chart-line"></i>
                        <span>Charts</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="#">Pie chart</a>
                            </li>
                            <li>
                                <a href="#">Line chart</a>
                            </li>
                            <li>
                                <a href="#">Bar chart</a>
                            </li>
                            <li>
                                <a href="#">Histogram</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-globe"></i>
                        <span>Maps</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="#">Google maps</a>
                            </li>
                            <li>
                                <a href="#">Open street map</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="header-menu">
                    <span>Extra</span>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-folder"></i>
                        <span>Wedding 婚禮邀請函</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-book"></i>
                        <span>Documentation</span>
                        <span class="badge badge-pill badge-primary">Beta</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-folder"></i>
                        <span>邀請函清單</span>
                    </a>
                </li>

            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
        <a href="#">
            <i class="fa fa-bell"></i>
            <span class="badge badge-pill badge-warning notification">3</span>
        </a>
        <a href="#">
            <i class="fa fa-envelope"></i>
            <span class="badge badge-pill badge-success notification">7</span>
        </a>
        <a href="#">
            <i class="fa fa-cog"></i>
            <span class="badge-sonar"></span>
        </a>
        <a href="/logout" class="logout_btn">
            <i class="fa fa-power-off"></i>
        </a>
    </div>
</nav>

invitingly/templates/info/adminlogin1.html
{% extends 'basepage.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}


<style media="screen">
body {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    background: linear-gradient(to right, #b92b27, #1565c0)
}

.box {
    width: 500px;
    padding: 40px;
    position: absolute;
    top: 50%;
    left: 50%;
    background: #191919;

    text-align: center;
    transition: 0.25s;
    margin-top: 100px
}

.box input[type="text"],
.box input[type="password"] {
    border: 0;
    background: none;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #3498db;
    padding: 10px 10px;
    width: 250px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s
}

.box h1 {
    color: white;
    text-transform: uppercase;
    font-weight: 500
}

.box input[type="text"]:focus,
.box input[type="password"]:focus {
    width: 300px;
    border-color: #2ecc71
}

.box input[type="submit"] {
    border: 0;
    background: none;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #2ecc71;
    padding: 14px 40px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s;
    cursor: pointer
}

.box input[type="submit"]:hover {
    background: #2ecc71
}

</style>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form class="box" method="post">
                    {% csrf_token %}
                    <h1>Admin Login</h1>
                    <p class="text-muted">請輸入您的登錄名和密碼!!!</p>

                    {% render_field form.username class="form-control" placeholder="Username" %}
                    {% render_field form.password class="form-control" placeholder="Password" %}

                    <input type="submit" name="" value="Login">

                </form>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br>


{% endblock %}

invitingly/templates/info/contactus.html
{% extends 'basepage.html' %}
{% load static %}

{% block content %}
<br><br><br><br>
<center>
    <h3 class='alert alert-success' style="margin-bottom:0px;">Send Us Your Valuable Feedback !</h3>
</center>

<section class="hero is-fullheight">
    <div class="hero-body" style="text-align: center">
        <div class="container">
            <center>
<!--                <h3 class='alert alert-success'>Send Us Your Valuable Feedback !</h3>-->

                <form method="POST" autocomplete="off">
                    <!-- Very Important csrf Token -->
                    {% csrf_token %}
                    <div class="form-group">
                        <p>
                            <h3>{{ form.as_p }}</h3>
                        </p>
                        <br>
                        <input type="submit" value="Send Message" class='btn btn-primary btn-lg'>
                    </div>
                </form>
            </center>
        </div>
    </div>
</section>

{% endblock %}

invitingly/templates/info/contactussuccess.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <style media="screen">
    .jumbotron {
      margin-bottom: 0px;
    }

    .jumbotron h1 {
      text-align: center;
    }
  </style>

</head>

<body>

  {% include "quiz/navbar.html" %}
  <br><br>
  <div class="jumbotron">
    <h1 class="display-4">您的消息發送成功!</h1>
    <p class="lead">我們會盡快回覆您的反饋</p>
    <hr class="my-4">
    <p>檢查網站的其他功能 !</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="/" role="button">首頁</a>
    </p>
  </div>

  {% include "quiz/footer.html" %}
</body>

</html>

invitingly/templates/info/frontpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
      *{
        font-family: 'Quicksand', sans-serif; 
      }
    </style>
  </head>
  <body>
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'frontpage' %}">
          <img src="https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/django.png" width="30px" height="200px">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Home
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">     
            {% if request.user.is_authenticated %}
              <a class="has-text-light mr-2">
                Welcome, "{{ user.username }}"
              </a>
              <div class="buttons">
                <a href="{% url 'logout' %}" class="button is-danger">
                  <strong>Logout</strong>
                </a>
                {% else %}
                <a href="{% url 'signup' %}" class="button is-success mr-2">
                  <strong>Sign up</strong>
                </a>
                <a href="{% url 'login' %}" class="button is-light">
                  Log in
                </a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
      </nav>

      <section class="hero is-medium is-large">
        <div class="hero-head">
          <div class="hero-body">
        <div class="container has-text-centered">
          <img src="https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/django.png" width="150" height="40">
          <h2 class="subtitle has-text-dark">
            Reset Password using SendGrid!
          </h2>
        </div>
      </div>
    </section>
  </body>
</html>

invitingly/templates/info/fuck.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<style>


<!--    *{-->
<!--        outline: 1px sold red !important;-->
<!---->
<!--    }-->


</style>
<body>

</body>
</html>

invitingly/templates/info/reset_password.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
      *{
        font-family: 'Quicksand', sans-serif; 
      }
    </style>
  </head>
  <body>
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'frontpage' %}">
          <img src="https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/django.png" width="30px" height="200px">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a href="{% url 'frontpage' %}" class="navbar-item">
            Home
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">     
            {% if request.user.is_authenticated %}
              <a class="has-text-light mr-2">
                Welcome, "{{ user.username }}"
              </a>
              <div class="buttons">
                <a href="{% url 'logout' %}" class="button is-danger">
                  <strong>Logout</strong>
                </a>
                {% else %}
                <a href="{% url 'signup' %}" class="button is-success mr-2">
                  <strong>Sign up</strong>
                </a>
                <a href="{% url 'login' %}" class="button is-light">
                  Log in
                </a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
      </nav>

    <!--new form-->
    <section class="hero is-dark is-fullheight">
      <div class="hero-body">
        <div class="container">
          <div class="columns is-centered">
            <div class="column is-5-tablet is-4-desktop is-3-widescreen">

              <form method="POST" action="." class="box">
                {% csrf_token %}

                <h1 class="has-text-centered mb-5 is-size-3">Reset Password</h1>

                <div class="field">
                  <label for="" class="label">Enter your email address</label>
                  <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left">
                      <i class="fa fa-envelope"></i>
                    </span>
                  </div>
                </div>

                <div class="field">
                  <button class="button is-success" type="submit">
                    Reset password
                  </button>
                </div>
              </form>
              
            </div>
          </div>
        </div>
      </div>
    </section>
 </body>
</html>