invitingly/invite/urls.py
from django.urls import path

from . import views

app_name = "invite"

# Create your urls here.
urlpatterns = [
    # path('', views._view, name=''),
    path('questionclick', views.questionclick_view, name="questionclick_view"),
    path('givemoneyclick', views.givemoney_view, name="givemoney_view"),
    path('notattendclick', views.notattend_view, name="notattend_view"),
]

invitingly/invitingly/urls.py
from django.contrib import admin
# from invitingly import *
from django.contrib.auth import views
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from information.forms import UserLoginForm, ResetPasswordForm, NewPasswordForm
from information.views import home_view, aboutus_view, contactus_view, afterlogin_view, adminclick_view, \
    admin_signup_view, admin_dashboard_view

urlpatterns = [
    # add a app
    path('', include('information.urls')),
    # path('student/', include('student.urls')),
    path('calendarMonths/', include('calendarMonths.urls')),
    path('invite/', include('invite.urls')),

    path('admin/', admin.site.urls),


    # 未加入會員的 navbars 可供新客戶觀看
    path('', home_view, name='home'),
    path('logout', LogoutView.as_view(template_name='info/logout.html'), name='logout'),
    # path('logout/', views.LogoutView.as_view(), name="logout"),

    path('aboutus', aboutus_view, name='aboutus'),
    path('contactus', contactus_view, name='contactus'),
    path('afterlogin', afterlogin_view, name='afterlogin'),

    path('adminclick', adminclick_view, name='adminclick'),
    path('adminlogin', LoginView.as_view(template_name='info/adminlogin.html', authentication_form=UserLoginForm), name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=UserLoginForm),name="login"),

    path('adminsignup', admin_signup_view, name='adminsignup'),
    # path('signup/', signup, name="signup"),

    path('admin-dashboard', admin_dashboard_view, name='admin-dashboard'),
    # path('adminlogin', LoginView.as_view(template_name='info/login.html'), authentication_form=AdminUserLoginForm, name='adminlogin'),
    # path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=AdminUserLoginForm),name="login"),


    # 對於忘記密碼 可以有另一個分支
    path('password-reset/',
         views.PasswordResetView.as_view(template_name="info/reset_password.html", form_class=ResetPasswordForm),
         name="password_reset"),

    path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name="info/reset_password_done.html"),
         name="password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name="info/reset_password_confirm.html",
                                                form_class=NewPasswordForm), name="password_reset_confirm"),

    path('password-reset-complete/',
         views.PasswordResetCompleteView.as_view(template_name="info/reset_password_complete.html"),
         name="password_reset_complete"),

]

invitingly/invite/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
BridegRoom = '新郎'
Bride = '新娘'
MutualFriend = '共同朋友'

FRIEND_CHOICE = (
    (BridegRoom, '新郎'),  # 會去現場
    (Bride, '新娘'),  # 送禮人未到
    (MutualFriend, '共同友人'),  # 禮人都拒絕
)

Meat = '葷食'
Vegetarian = '素食'

DIET_CHOICE = (
    (Meat, '葷食'),  # 會去現場
    (Vegetarian, '素食'),  # 送禮人未到
)

Zero = '0'
One = '1'
Two = '2'
Three = '3'
Four = '4'

SEAT_CHOICE = (
    (Zero, '0'),
    (One, '1'),
    (Two, '2'),
    (Three, '3'),
    (Four, '4'),

)


class Invite(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    # user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    autono = models.AutoField(primary_key=True, verbose_name="編號")
    name = models.CharField(help_text='ex: 王小明', max_length=255, null=False, blank=False,
                            verbose_name="真實姓名")
    phone = PhoneNumberField(unique=True, default=None, null=False, blank=False, verbose_name="電話",
                             help_text='ex: +886928420424')
    address = models.CharField(help_text='ex: 台北市信義區松高路12號3樓 ', max_length=255, null=True, blank=True,
                               verbose_name="地址")
    email = models.EmailField(help_text='ex: admin123@gmail.com', max_length=255, null=True, blank=True,
                              verbose_name="信箱")
    know = models.CharField(help_text='勾選一個', max_length=4, choices=FRIEND_CHOICE,
                            verbose_name="認識新人哪位")
    diet = models.CharField(help_text='勾選一個 ', max_length=2, choices=DIET_CHOICE,
                            verbose_name="飲食偏好")
    baby_seat = models.CharField(help_text='勾選一個 ', max_length=1, choices=SEAT_CHOICE,
                                 verbose_name="嬰兒座椅數量")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="建立時間")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="更新時間")
    status = models.BooleanField(default=True, verbose_name="狀態")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "inv_invitation"
        ordering = ('-created_at',)
        verbose_name = "邀請函"
        verbose_name_plural = "邀請函建立"


class GiveMoney(models.Model):
    autonoGive = models.AutoField(primary_key=True, verbose_name="編號")
    nameGive = models.CharField(help_text='ex: 王小明', max_length=255, null=True, blank=True,
                                verbose_name="真實姓名")
    phoneGive = PhoneNumberField(unique=True, default=None, null=False, blank=False, verbose_name="電話",
                                 help_text='ex: +886928420424')
    addressGive = models.CharField(help_text='ex: 台北市信義區松高路12號3樓 ', max_length=255, null=True, blank=True,
                                   verbose_name="地址")
    emailGive = models.EmailField(help_text='ex: admin123@gmail.com', max_length=255, null=True, blank=True,
                                  verbose_name="信箱")
    status = models.BooleanField(default=True, verbose_name="狀態")

    def __str__(self):
        return self.nameGive

    class Meta:
        db_table = "inv_givemoney"
        ordering = ('-phoneGive',)
        verbose_name = "給禮金"
        verbose_name_plural = "給禮金建立"


class NotAttend(models.Model):
    autonoNo = models.AutoField(primary_key=True, verbose_name="編號")
    nameNo = models.CharField(help_text='ex: 王小明', max_length=255, null=True, blank=True,
                              verbose_name="真實姓名")
    emailNo = models.EmailField(help_text='ex: admin123@gmail.com', max_length=255, null=True, blank=True,
                                verbose_name="信箱")
    msgNo = models.CharField(help_text='ex: 給新人一段祝福語 ', max_length=255, null=True, blank=True,
                             verbose_name="留言")
    status = models.BooleanField(default=True, verbose_name="狀態")

    def __str__(self):
        return self.nameNo

    class Meta:
        db_table = "inv_notattend"
        ordering = ('-emailNo',)
        verbose_name = "拒絕參加留言板"
        verbose_name_plural = "留言板 建立"

invitingly/invite/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


# Create your forms here.
class InvitationUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password']
        widgets = {
            # 'password': forms.PasswordInput(attrs={'required': False}),
            'password': forms.PasswordInput(attrs={'placeholder': '密碼輸入'}),
        }


class InvitationForm(forms.ModelForm):
    class Meta:
        model = models.Invitation
        fields = ['name', 'phone', 'address', 'email', 'know', 'diet', 'baby_seat', ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入姓名'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入電話'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入地址'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '輸入信箱'}),
            # 在這裡為其他字段添加相應的小工具
        }



class GiveMoneyForm(forms.ModelForm):
    class Meta:
        model = models.GiveMoney
        fields = ['autonoGive', 'nameGive', 'phoneGive', 'addressGive', 'emailGive', 'status']

        widgets = {
            'nameGive': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入姓名'}),
            'phoneGive': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入電話'}),
            'addressGive': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入地址'}),
            'emailGive': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '輸入信箱'}),
            # 在這裡為其他字段添加相應的小工具
        }


class NotAttendForm(forms.ModelForm):
    class Meta:
        model = models.NotAttend
        fields = ['autonoNo', 'nameNo', 'emailNo', 'msgNo', 'status']

        widgets = {
            'nameNo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入姓名'}),
            'emailNo': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '輸入信箱'}),
            'msgNo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '輸入地址'}),
            # 在這裡為其他字段添加相應的小工具
        }

invitingly/invite/views.py
from django.http import HttpResponse
from django.shortcuts import render

from invite.models import *


# Create your views here.
def questionclick_view(request):
    templates_name = 'invite/questionclick.html'
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        email = request.POST.get('email')
        know = request.POST.get('know')
        diet = request.POST.get('diet')
        baby_seat = request.POST.get('baby_seat')

        # 檢查必填欄位是否為空
        if not name or not phone or not address or not email or not know:
            return HttpResponse(
                '請填寫所有必填欄位！ 點擊<a style="text-decoration: none" href=""><b style="font-size:20px">_返回</b></a>連到 邀請函填寫<br>')

        # 檢查電話號碼是否已經存在
        if Invite.objects.filter(phone=phone).exists():
            return HttpResponse(
                '邀請函創建成功，電話號碼已儲存。 點擊<a style="text-decoration: none" href="/"><b style="font-size:20px">返回</b></a>連到 首頁<br>')

        # 創建新的邀請對象
        invite = Invite(name=name, phone=phone, address=address, email=email, know=know, diet=diet,
                        baby_seat=baby_seat, )
        invite.save()
        return HttpResponse(
            '邀請函創建成功!!! 請點擊<a style="text-decoration: none" href="/"><b style="font-size:20px">返回</b></a>連到 首頁<br>')
    else:
        context = {
            'title': '邀請函 建立',
        }
        # 如果是 GET 請求，回傳 render 函式 ; # 如果是GET請求，返回表單
        return render(request, templates_name, context)


def survey_thankyou(request):
    return render(request, 'questionnaire/thankyou.html')


def givemoney_view(request):
    templates_name = 'invite/givemoneyclick.html'
    if request.method == 'POST':
        nameGive = request.POST.get('nameGive')
        phoneGive = request.POST.get('phoneGive')
        addressGive = request.POST.get('addressGive')
        emailGive = request.POST.get('emailGive')

        if GiveMoney.objects.filter(phoneGive=phoneGive).exists():
            return HttpResponse(
                '邀請函創建成功，電話號碼已儲存。 點擊<a style="text-decoration: none" href="/"><b style="font-size:20px">返回</b></a>連到 首頁<br>')

        givemoney = GiveMoney(nameGive=nameGive, phoneGive=phoneGive, addressGive=addressGive, emailGive=emailGive)
        givemoney.save()
        return HttpResponse(
            '邀請函創建成功!!! 請點擊<a style="text-decoration: none" href="/"><b style="font-size:20px">返回</b></a>連到 首頁<br>')
    else:
        context = {
            'title': '給錢 建立',
        }
        return render(request, templates_name, context)


def notattend_view(request):
    templates_name = 'invite/notattendclick.html'
    if request.method == 'POST':
        nameNo = request.POST.get('nameNo')
        emailNo = request.POST.get('emailNo')
        msgNo = request.POST.get('msgNo')

        notattend = NotAttend(nameNo=nameNo, emailNo=emailNo, msgNo=msgNo, )
        notattend.save()
        return HttpResponse(
            '邀請函創建成功!!! 請點擊<a style="text-decoration: none" href="/"><b style="font-size:20px">返回</b></a>連到 首頁<br>')
    else:
        context = {
            'title': '留言板 建立',
        }
        return render(request, templates_name, context)

invitingly/templates/invite/givemoneyclick2.html
{% load static %}
<form method="POST" action="{% url 'invite:givemoney_view' %}" id="theFormB" class="givemoney-form">
    {% csrf_token %}

    <fieldset class="givemoney">
        <h3>不克前去但會給予禮金。</h3>
        <input name="givemoney" type="radio" id="givemoneyYes" value="yes" class="radio-givemoney--yes"
               style="display: none"
               checked/>
        <label for="bringingYes" class="label-givemoney--yes" style="display: none">Yes!</label>

        <div class="is_givemoney" id="givemoney">
            <h4>謝謝您，如下資料填寫，會幫您作登記?</h4>
            <p class="subtitle"></p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="pencil2">
                        <i class="fa fa-pencil fa-fw fa-lg" aria-hidden="true"></i>
                        <img src="{% static 'image/pencil.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="nameGive" type="text" placeholder="姓名" aria-label="Username"
                       aria-describedby="invite-money1">
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="phone2">
                        <i class="fa fa-phone fa-fw fa-lg"></i>
                        <img src="{% static 'image/phone.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="phoneGive" type="text" placeholder="連絡電話" aria-label="Phone"
                       aria-describedby="invite-money2">
            </div>
            <p class="h12">希望以什麼方式收到喜帖? (擇一填寫)</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="map-marker2">
                        <i class="fa fa-map-marker fa-fw fa-lg"></i>
                        <img src="{% static 'image/placeholder.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="addressGive" type="text"
                       placeholder="請輸入地址&nbsp;&nbsp;ex: 104 台北市敬業路三段5號10樓"
                       aria-label="address"
                       aria-describedby="invite-money3-1">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="envelope2">
                        <i class="fa fa-envelope-o fa-fw fa-lg"></i>
                        <img src="{% static 'image/address.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="emailGive" type="text"
                       placeholder="請輸入郵件帳號&nbsp;&nbsp;ex: abc123@gmail.com"
                       aria-label="E-mail"
                       aria-describedby="invite-money3-2">
            </div>
            <p class="h12">禮金付款方式?</p>
            <div class="input-group mb-3 a">
                <div class="container">
                    <div class="row g-2">
                        <div class="col-6">
                            <div class="p-3 border bg-light">
                                <p>ATM 轉帳(臨櫃)匯款帳戶 :</p>
                                <p>
                                    <span>中國信託 - 城東分行</span><br>
                                    <span>銀行代碼：822</span><br>
                                    <span>帳號：071540261312</span><br>
                                </p>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="p-3 border bg-light">
                                <span>郵局匯款(臨櫃)帳戶 :</span>
                                <p>
                                    <span>銀行代號：700 (郵局)</span><br>
                                    <span>局號（含檢號）：1234567</span><br>
                                    <span>帳號（含檢號）：8901234</span><br>
                                    <span>戶名：陳阿鳩</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <p class="h12">運用地址寄送，後續再與我們提醒與通知: </p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="basic-addon1">
                        <i class="fa fa-map-marker fa-fw fa-lg"></i>
                    </span>
                </div>
                <input type="text" disabled="disabled" placeholder="地址: 10491台北市中山區敬業三路20號"
                       aria-label="address"
                       aria-describedby="basic-addon1">
            </div>
            <span>ATM或臨櫃匯款後通知，如下: </span>
            <p class="h12">請 mail 到 信箱 並請在內容提供您的<br><span
                    class="low-highlight">戶名(全名)、匯款日期、金額 以及您的 帳號末五碼</span>，謝謝!
            </p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="basic-addon1">
                        <i class="fa fa-envelope-o fa-fw fa-lg"></i>
                    </span>
                </div>
                <input type="text" disabled="disabled"
                       placeholder="信箱: wleejan982@hotmail.com"
                       aria-label="E-mail"
                       aria-describedby="basic-addon1">
            </div>

        </div>

        <input name="givemoney" type="radio" value="no" id="givemoneyNo" class="radio-givemoney--no"
               style="display: none"/>
        <label for="givemoneyNo" class="label-givemoney--no" style="display: none">No, I'm the lone ranger</label>
        <div class="mb-3">
            <button class="send-card-button" id="theButtonB">送出☆</button>
            <div id="thankyou" class="thank-you"></div>
        </div>
    </fieldset>
</form>

invitingly/templates/invite/inviteCreate.html
{% extends 'base.html' %}

{% block title %}
    填寫{{ title }}
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}


    <div class="page-content">
        <div class="container-fluid">
            <h2>{{ title }}</h2>
            <hr>
            <div class="row">
                <div class="form-group col-md-12">
                    <p>This is a responsive sidebar template with dropdown menu based on bootstrap 4 framework.</p>
                    <p> You can find the complete code on <a href="https://github.com/azouaoui-med/pro-sidebar-template"
                                                             target="_blank">
                        Github</a>, it contains more themes and background image option</p>
                </div>
                <div class="form-group col-md-12">
                    <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=star&count=true&size=small"
                            frameborder="0" scrolling="0" width="90px" height="30px"></iframe>
                    <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=fork&count=true&size=small"
                            frameborder="0" scrolling="0" width="90px" height="30px"></iframe>
                </div>
                <div class="form-group col-md-12">
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">New !</h4>
                        <p>New react pro sidebar library is now available on <a
                                href="https://www.npmjs.com/package/react-pro-sidebar" target="_blank">npm</a> <a
                                href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                            <img alt="GitHub stars"
                                 src="https://img.shields.io/github/stars/azouaoui-med/react-pro-sidebar?style=social"/>
                        </a></p>
                        <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank"
                           class="btn btn-sm btn-primary mr-2">
                            Github</a>
                        <a href="https://azouaoui-med.github.io/react-pro-sidebar" target="_blank"
                           class="btn btn-sm btn-success">
                            Demo</a>

                    </div>

                </div>
            </div>
            <h5>More templates</h5>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    {# <div class="card rounded-0 p-0 shadow-sm"></div>#}
                    <!--Django Model Form-->
                    <h2 class="my-4">Add a new movie</h2>




                    <form method="POST">
                        {% csrf_token %}
                        {{ invite_form|crispy }}
{#                        {{ invite_form.as_p }}#}
                        <button class="btn btn-primary my-4" value="save" type="submit">送出</button>
                    </form>
                    <!--Django Model-->





                    <div class="row">
                            {% for m in invite %}
                                <div class="col-lg-4 col-md-6 col-sm-12 pb-4">
                                    <div class="card h-100 p-4">
{#                                        <img src="{{ m.movie_poster.url }}" class="card-img-top"#}
{#                                             alt="{{ m.movie_title }}">#}
                                        <h4>{{ m.rsvpName }}</h4>
                                        <h4>{{ m.rsvpPhone }}</h4>
                                        <h4>{{ m.rsvpAddress }}</h4>
                                        <h4>{{ m.rsvpEmail }}</h4>
{#                                        <p class="text-muted">{{ m.release_year }} | {{ m.director }}</p>#}
{#                                        <p>{{ m.movie_plot }}</p>#}
                                    </div>
                                </div>
                            {% empty %}
                                <p>沒有添加電影。</p>
                            {% endfor %}
                        </div>

                </div>
            </div>
            <hr>

            <footer class="text-center">
                <div class="mb-2">
                    <small>
                        © 2020 made with <i class="fa fa-heart" style="color:red"></i> by - <a target="_blank"
                                                                                               rel="noopener noreferrer"
                                                                                               href="https://azouaoui.netlify.com">
                        Mohamed Azouaoui
                    </a>
                    </small>
                </div>
                <div>
                    <a href="https://github.com/azouaoui-med" target="_blank">
                        <img alt="GitHub followers"
                             src="https://img.shields.io/github/followers/azouaoui-med?label=github&style=social"/>
                    </a>
                    <a href="https://twitter.com/azouaoui_med" target="_blank">
                        <img alt="Twitter Follow"
                             src="https://img.shields.io/twitter/follow/azouaoui_med?label=twitter&style=social"/>
                    </a>
                </div>
            </footer>
        </div>
    </div>
{% endblock %}

invitingly/templates/invite/notattendclick.html
{% load static %}
<form method="POST" action="{% url 'invite:notattend_view' %}" id="theFormC" class="notattending-form">
    {% csrf_token %}
    <fieldset class="notattending">
        <h3>可以留言給予新人祝福嗎?</h3>
        <input name="notattending" type="radio" id="notattendingYes" value="yes"
               class="radio-notattending--yes" style="display: none"
               checked/>
        <label for="notattendingYes" class="label-notattending--yes" style="display: none">Yes!</label>

        <div class="is_notattending" id="notattending">
            <h4>可惜了，無法前來但可寫下您的祝福!!!</h4>
            <p class="subtitle">祝福新人們的一句話。</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="basic-addon1">
<!--                        <i class="fa fa-pencil fa-fw fa-lg" aria-hidden="true"></i>-->
                        <img src="{% static 'image/pencil.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="nameNo" type="text" placeholder="姓名" aria-label="Username"
                       aria-describedby="basic-addon1">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="basic-addon1">
<!--                        <i class="fa fa-envelope fa-fw fa-lg" aria-hidden="true"></i>-->
                        <img src="{% static 'image/address.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="emailNo" type="text" placeholder="信箱帳號" aria-label="email"
                       aria-describedby="nameHelpBlock3">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="basic-addon1">
<!--                        <i class="fa fa-commenting fa-fw fa-lg" aria-hidden="true"></i>-->
                        <img src="{% static 'image/chat.png'%}" width="45" height="45">
                    </span>
                </div>
                <textarea name="msgNo" class="radio-div" placeholder="我要留言" rows="2"></textarea>
            </div>
            <div class="mb-3">
                <button class="send-card-button" id="theButtonC">送出留言!</button>
                <div id="thankyou" class="thank-you"></div>
            </div>
        </div>
    </fieldset>

</form>

invitingly/templates/invite/notattendclick2.html
{% load static %}
<form method="POST" action="{% url 'invite:notattend_view' %}" id="theFormC" class="notattending-form">
    {% csrf_token %}
    <fieldset class="notattending">
        <h3>可以留言給予新人祝福嗎?</h3>
        <input name="notattending" type="radio" id="notattendingYes" value="yes"
               class="radio-notattending--yes" style="display: none"
               checked/>
        <label for="notattendingYes" class="label-notattending--yes" style="display: none">Yes!</label>

        <div class="is_notattending" id="notattending">
            <h4>可惜了，無法前來但可寫下您的祝福!!!</h4>
            <p class="subtitle">祝福新人們的一句話。</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="pencil3">
                        <i class="fa fa-pencil fa-fw fa-lg" aria-hidden="true"></i>
                        <img src="{% static 'image/pencil.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="nameNo" type="text" placeholder="姓名" aria-label="Username"
                       aria-describedby="invite-notattend1">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="envelope3">
                        <i class="fa fa-envelope fa-fw fa-lg" aria-hidden="true"></i>
                        <img src="{% static 'image/address.png'%}" width="45" height="45">
                    </span>
                </div>
                <input name="emailNo" type="text" placeholder="信箱帳號" aria-label="email"
                       aria-describedby="invite-notattend2">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="inputicon" id="commenting3">
                        <i class="fa fa-commenting fa-fw fa-lg" aria-hidden="true"></i>
                        <img src="{% static 'image/chat.png'%}" width="45" height="45">
                    </span>
                </div>
                <textarea name="msgNo" class="radio-div" placeholder="我要留言" rows="2" aria-describedby="invite-notattend3"></textarea>
            </div>
            <div class="mb-3">
                <button class="send-card-button" id="theButtonC">送出留言!</button>
                <div id="thankyou" class="thank-you"></div>
            </div>
        </div>
    </fieldset>

</form>

invitingly/templates/invite/update_student.html
{% extends 'quiz/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}
<head>
  <style media="screen">
    input[type=text], select,input[type=number] ,input[type=password], textarea{
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }


  </style>


</head>

<br><br>
<h3 style="text-align:center;">UPDATE STUDENT 更新學生</h3>
<div>
  <form method="post" autocomplete="off" enctype="multipart/form-data" style="margin-left:200px;margin-right:200px;">
      {% csrf_token %}
        <label for="first_name">名</label>
        {% render_field userForm.first_name class="form-control" placeholder="小名" %}
        <label for="last_name">姓氏</label>
        {% render_field userForm.last_name class="form-control" placeholder="ex: 陳" %}
          <label for="mobile">手機</label>
          {% render_field studentForm.mobile class="form-control" placeholder="ex: 0911123123" %}
            <label for="address">地址</label>
          {% render_field studentForm.address class="form-control" placeholder="ex: 114台北市內湖區成功路四段173號2樓" %}

        <label for="username">使用者名稱</label>
        {% render_field userForm.username class="form-control" placeholder="ex: admin" %}
          <label for="password">密碼</label>
        {% render_field userForm.password class="form-control" placeholder="密碼輸入" %} <br><br>
        <label for="profile_pic">頭像</label>
          {% render_field studentForm.profile_pic class="form-control" placeholder="頭像照片" %}
<br><br>
    <input type="submit" value="Update">
  </form>
</div>



<br><br><br><br><br><br><br><br>
{% endblock content %}